### ISSUE TITLE
Make another release

### ISSUE THREAD

**Issue by mimi89999** [otakuchiyan/Wifi-Key-View#10]
Make another release because 1.2 doesn't include my PR. It could be named 1.3...

**Comment by otakuchiyan** [comment]
Your pull request had just changed a variable, so needn't to release.

**Comment by mimi89999** [comment]
V1.2 was released jul8. I made several PR in the meantime.

**Comment by mimi89999** [comment]
The F-droid version is built from sourcecode of the release. So no support of material design... (I made my PR later).
![tmp_22156-screenshot_2015-11-08-16-39-451006318653](https://cloud.githubusercontent.com/assets/8530546/11021096/5a47b6b2-8637-11e5-866d-b79350817bba.png)

**Comment by mimi89999** [comment]
:(

**Comment by otakuchiyan** [comment]
Sorry, I forgot your pull request about material design.
I will make another release.

**Comment by mimi89999** [comment]
And before making release 1.3 change AndroidManifest.xml

**Comment by mimi89999** [comment]
So that 1.3 shows as 1.3

**Comment by otakuchiyan** [comment]
I think the version should be 1.2.1, because it just changed UI.

**Comment by mimi89999** [comment]
18 commits were made since release v1.2
